# Generated by Django 5.0 on 2023-12-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='github_url',
            field=models.URLField(blank=True, help_text='Enter the website URL', null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Enter the website URL', null=True),
        ),
    ]
