# Generated by Django 5.0 on 2023-12-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_info_github_url_info_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gmail_mail',
            field=models.URLField(blank=True, help_text='Enter the website URL', null=True),
        ),
    ]
