# Generated by Django 5.0 on 2023-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0003_info_gmail_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gmail_mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
