# Generated by Django 5.0 on 2023-12-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0004_alter_info_gmail_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='gmail_mail',
        ),
    ]
