# Generated by Django 5.0 on 2023-12-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0005_remove_info_gmail_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
