# Generated by Django 5.0 on 2023-12-30 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0006_alter_info_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(default='Your skills ', max_length=255)),
                ('about_skill', models.TextField(max_length=300, null=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutme.info')),
            ],
        ),
    ]
