# Generated by Django 5.0 on 2023-12-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0007_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill1',
            new_name='skill',
        ),
    ]
