# Generated by Django 5.0 on 2023-12-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0008_rename_skill1_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='about_skill',
        ),
    ]
