# Generated by Django 5.0 on 2023-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0009_remove_skills_about_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='experience',
            field=models.CharField(default='Your experience years ', max_length=255),
        ),
    ]
