# Generated by Django 5.0 on 2023-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0011_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, help_text='Enter the project URL', null=True),
        ),
    ]
