# Generated by Django 5.0 on 2023-12-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0012_project_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
        migrations.AddField(
            model_name='project',
            name='picture_snap',
            field=models.ImageField(blank=True, help_text='Upload an image file (JPEG, PNG, etc.)', null=True, upload_to='project'),
        ),
    ]
